### ISSUE TITLE
np.gradient(cases) != daily new cases

### ISSUE THREAD

**Issue by Merano01** [cmoestl/sars2_austria#1]
daily new cases are not accurate; for march you will get 550 instead of 430

I think you need the delta between the daily totals from the input data instead of np.gradient (whatever this exactly does)

**Comment by Merano01** [comment]
ok, I did some research what gradient does and it can make sense for your charts to even out the curve; but then I would not name it "daily new cases"

**Comment by Merano01** [comment]
I fixed it for me with:
ax2.bar(dates[1:],np.diff(cases),color='tomato',label=country+' daily new cases')

**Comment by cmoestl** [comment]
indeed, thanks for pointing this out. I now changed the daily new cases to using np.diff and adding a 0 at the beginning + adding a running mean of 4 days for the daily new cases for both Austria and South Korea. This should smooth out to some degree inconsistencies on how the daily reported numbers are made.
This shows the especially at later times South Korea daily new cases is very well described by a Gaussian fit, for Austria its too early now for the Gaussian fit as the numbers still rise.
